////////////////////////////////////
// definintions come from: https://chromium.googlesource.com/chromium/src/+/HEAD/net/log/net_log_event_type_list.h
export type NetlogEventParams = {
  REQUEST_ALIVE: undefined                      // type 2
  URL_REQUEST_START_JOB: {                      // type 106
    url: string
    method: "GET" | "POST" | "PUT" | "DELETE" | "HEAD" | "OPTIONS" | "PATCH"
    initiator: string | "not an origin"
    load_flags: number
    network_isolation_key: string
    request_type: "main frame" | "sub frame" | "other"
    priority?: number
    site_for_cookies: string
    traffic_annotation?: number
    upload_id?: string
    net_error?: number      // only when there's an error
  }
  HTTP_TRANSACTION_SEND_REQUEST_HEADERS: {      // type 171
    headers: string[]       // "Host: google.com", "Connection: keep-alive", ...
    line: string            // "GET / HTTP/1.1\r\n"
  },
  HTTP_TRANSACTION_HTTP2_SEND_REQUEST_HEADERS: {
    headers: string[]       // "Host: google.com", "Connection: keep-alive", ...
  },
  HTTP2_STREAM_UPDATE_SEND_WINDOW: {
    delta: number
    stream_id: number
    window_size: number
  },
  SSL_SOCKET_BYTES_SENT: {
    byte_count: number
    bytes: string   // base64 encoded
  },
  HTTP_TRANSACTION_READ_RESPONSE_HEADERS: {     // type 176
    headers: string[]       // "HTTP/1.1 200 OK", "Server: nginx", ...
  },
  HTTP_TRANSACTION_READ_BODY: undefined,
  URL_REQUEST_JOB_FILTERED_BYTES_READ: {
    byte_count: number
    bytes: string           // base64 encoded
  },
  HTTP_CACHE_READ_DATA: undefined,
  COOKIE_INCLUSION_STATUS: {
    status: string
    name: string
    domain: string
    path: string
    operation: "send" | "store"
  }
}

export interface NetlogJson {
  constants: Constants
  events: NetlogEvent<undefined>[]
}

interface Constants {
  activeFieldTrialGroups: string[]
  addressFamily: AddressFamily
  certPathBuilderDigestPolicy: CertPathBuilderDigestPolicy
  certStatusFlag: CertStatusFlag
  certVerifierFlags: CertVerifierFlags
  clientInfo: ClientInfo
  dnsQueryType: DnsQueryType
  loadFlag: LoadFlag
  loadState: LoadState
  logCaptureMode: string
  logEventPhase: LogEventPhase
  logEventTypes: LogEventTypes
  logFormatVersion: number
  logSourceType: LogSourceType
  netError: NetError
  quicError: QuicError
  quicRstStreamError: QuicRstStreamError
  secureDnsMode: SecureDnsMode
  timeTickOffset: number
}

interface AddressFamily {
  ADDRESS_FAMILY_IPV4: number
  ADDRESS_FAMILY_IPV6: number
  ADDRESS_FAMILY_UNSPECIFIED: number
}

interface CertPathBuilderDigestPolicy {
  kStrong: number
  kWeakAllowSha1: number
}

interface CertStatusFlag {
  AUTHORITY_INVALID: number
  CERTIFICATE_TRANSPARENCY_REQUIRED: number
  COMMON_NAME_INVALID: number
  CT_COMPLIANCE_FAILED: number
  DATE_INVALID: number
  INVALID: number
  IS_EV: number
  KNOWN_INTERCEPTION_BLOCKED: number
  KNOWN_INTERCEPTION_DETECTED: number
  NAME_CONSTRAINT_VIOLATION: number
  NON_UNIQUE_NAME: number
  NO_REVOCATION_MECHANISM: number
  PINNED_KEY_MISSING: number
  REVOKED: number
  REV_CHECKING_ENABLED: number
  SHA1_SIGNATURE_PRESENT: number
  SYMANTEC_LEGACY: number
  UNABLE_TO_CHECK_REVOCATION: number
  VALIDITY_TOO_LONG: number
  WEAK_KEY: number
  WEAK_SIGNATURE_ALGORITHM: number
}

interface CertVerifierFlags {
  VERIFY_DISABLE_NETWORK_FETCHES: number
}

interface ClientInfo {
  cl: string
  command_line: string
  name: string
  official: string
  os_type: string
  version: string
  version_mod: string
}

interface DnsQueryType {
  A: number
  AAAA: number
  HTTPS: number
  PTR: number
  SRV: number
  TXT: number
  UNSPECIFIED: number
}

interface LoadFlag {
  BYPASS_CACHE: number
  BYPASS_PROXY: number
  CAN_USE_RESTRICTED_PREFETCH: number
  DISABLE_CACHE: number
  DISABLE_CERT_NETWORK_FETCHES: number
  DISABLE_CONNECTION_MIGRATION_TO_CELLULAR: number
  DO_NOT_SAVE_COOKIES: number
  DO_NOT_USE_EMBEDDED_IDENTITY: number
  IGNORE_LIMITS: number
  MAIN_FRAME_DEPRECATED: number
  NORMAL: number
  ONLY_FROM_CACHE: number
  PREFETCH: number
  RESTRICTED_PREFETCH: number
  SKIP_CACHE_VALIDATION: number
  SKIP_VARY_CHECK: number
  SUPPORT_ASYNC_REVALIDATION: number
  VALIDATE_CACHE: number
}

interface LoadState {
  CONNECTING: number
  DOWNLOADING_PAC_FILE: number
  ESTABLISHING_PROXY_TUNNEL: number
  IDLE: number
  OBSOLETE_WAITING_FOR_APPCACHE: number
  READING_RESPONSE: number
  RESOLVING_HOST: number
  RESOLVING_HOST_IN_PAC_FILE: number
  RESOLVING_PROXY_FOR_URL: number
  SENDING_REQUEST: number
  SSL_HANDSHAKE: number
  WAITING_FOR_AVAILABLE_SOCKET: number
  WAITING_FOR_CACHE: number
  WAITING_FOR_DELEGATE: number
  WAITING_FOR_RESPONSE: number
  WAITING_FOR_STALLED_SOCKET_POOL: number
}

interface LogEventPhase {
  PHASE_BEGIN: number
  PHASE_END: number
  PHASE_NONE: number
}

interface LogEventTypes {
  AUTH_BOUND_TO_CONTROLLER: number
  AUTH_CHANNEL_BINDINGS: number
  AUTH_CONTROLLER: number
  AUTH_GENERATE_TOKEN: number
  AUTH_HANDLER_CREATE_RESULT: number
  AUTH_HANDLER_INIT: number
  AUTH_HANDLE_CHALLENGE: number
  AUTH_LIBRARY_ACQUIRE_CREDS: number
  AUTH_LIBRARY_BIND_FAILED: number
  AUTH_LIBRARY_IMPORT_NAME: number
  AUTH_LIBRARY_INIT_SEC_CTX: number
  AUTH_LIBRARY_LOAD: number
  BAD_PROXY_LIST_REPORTED: number
  BIDIRECTIONAL_STREAM_ALIVE: number
  BIDIRECTIONAL_STREAM_BOUND_TO_QUIC_SESSION: number
  BIDIRECTIONAL_STREAM_BYTES_RECEIVED: number
  BIDIRECTIONAL_STREAM_BYTES_SENT: number
  BIDIRECTIONAL_STREAM_BYTES_SENT_COALESCED: number
  BIDIRECTIONAL_STREAM_FAILED: number
  BIDIRECTIONAL_STREAM_READY: number
  BIDIRECTIONAL_STREAM_READ_DATA: number
  BIDIRECTIONAL_STREAM_RECV_HEADERS: number
  BIDIRECTIONAL_STREAM_RECV_TRAILERS: number
  BIDIRECTIONAL_STREAM_SENDV_DATA: number
  CANCELLED: number
  CERTIFICATE_DATABASE_CHANGED: number
  CERT_CT_COMPLIANCE_CHECKED: number
  CERT_VERIFIER_JOB: number
  CERT_VERIFIER_REQUEST: number
  CERT_VERIFIER_REQUEST_BOUND_TO_JOB: number
  CERT_VERIFIER_TASK: number
  CERT_VERIFIER_TASK_BOUND: number
  CERT_VERIFY_PROC: number
  CERT_VERIFY_PROC_ADDITIONAL_TRUST_ANCHOR: number
  CERT_VERIFY_PROC_CHROME_ROOT_STORE_VERSION: number
  CERT_VERIFY_PROC_INPUT_CERT: number
  CERT_VERIFY_PROC_PATH_BUILD_ATTEMPT: number
  CERT_VERIFY_PROC_PATH_BUILT: number
  CERT_VERIFY_PROC_TARGET_CERT: number
  CHECK_CORS_PREFLIGHT_CACHE: number
  CHECK_CORS_PREFLIGHT_REQUIRED: number
  COMPUTED_PRIVACY_MODE: number
  CONNECT_JOB: number
  CONNECT_JOB_SET_SOCKET: number
  CONNECT_JOB_TIMED_OUT: number
  COOKIE_GET_BLOCKED_BY_NETWORK_DELEGATE: number
  COOKIE_INCLUSION_STATUS: number
  COOKIE_PERSISTENT_STORE_CLOSED: number
  COOKIE_PERSISTENT_STORE_KEY_LOAD_COMPLETED: number
  COOKIE_PERSISTENT_STORE_KEY_LOAD_STARTED: number
  COOKIE_PERSISTENT_STORE_LOAD: number
  COOKIE_PERSISTENT_STORE_ORIGIN_FILTERED: number
  COOKIE_SET_BLOCKED_BY_NETWORK_DELEGATE: number
  COOKIE_STORE_ALIVE: number
  COOKIE_STORE_COOKIE_ADDED: number
  COOKIE_STORE_COOKIE_DELETED: number
  COOKIE_STORE_COOKIE_PRESERVED_SKIPPED_SECURE: number
  COOKIE_STORE_COOKIE_REJECTED_HTTPONLY: number
  COOKIE_STORE_COOKIE_REJECTED_SECURE: number
  COOKIE_STORE_SESSION_PERSISTENCE: number
  CORS_PREFLIGHT_CACHED_RESULT: number
  CORS_PREFLIGHT_ERROR: number
  CORS_PREFLIGHT_RESULT: number
  CORS_PREFLIGHT_URL_REQUEST: number
  CORS_REQUEST: number
  CREATED_BY: number
  CT_LOG_ENTRY_AUDITED: number
  DELEGATE_INFO: number
  DISK_CACHE_ENTRY_IMPL: number
  DISK_CACHE_MEM_ENTRY_IMPL: number
  DNS_CONFIG_CHANGED: number
  DNS_TRANSACTION: number
  DNS_TRANSACTION_ATTEMPT: number
  DNS_TRANSACTION_QUERY: number
  DNS_TRANSACTION_RESPONSE: number
  DNS_TRANSACTION_TCP_ATTEMPT: number
  ENTRY_CLOSE: number
  ENTRY_DOOM: number
  ENTRY_READ_DATA: number
  ENTRY_WRITE_DATA: number
  FAILED: number
  FTP_COMMAND_SENT: number
  FTP_CONTROL_CONNECTION: number
  FTP_CONTROL_RESPONSE: number
  FTP_DATA_CONNECTION: number
  HOST_CACHE_PERSISTENCE_START_TIMER: number
  HOST_CACHE_PREF_READ: number
  HOST_CACHE_PREF_WRITE: number
  HOST_RESOLVER_MANAGER_ATTEMPT_FINISHED: number
  HOST_RESOLVER_MANAGER_ATTEMPT_STARTED: number
  HOST_RESOLVER_MANAGER_CACHE_HIT: number
  HOST_RESOLVER_MANAGER_CONFIG_PRESET_MATCH: number
  HOST_RESOLVER_MANAGER_CREATE_JOB: number
  HOST_RESOLVER_MANAGER_DNS_TASK: number
  HOST_RESOLVER_MANAGER_DNS_TASK_EXTRACTION_FAILURE: number
  HOST_RESOLVER_MANAGER_DNS_TASK_TIMEOUT: number
  HOST_RESOLVER_MANAGER_HOSTS_HIT: number
  HOST_RESOLVER_MANAGER_IPV6_REACHABILITY_CHECK: number
  HOST_RESOLVER_MANAGER_JOB: number
  HOST_RESOLVER_MANAGER_JOB_ATTACH: number
  HOST_RESOLVER_MANAGER_JOB_EVICTED: number
  HOST_RESOLVER_MANAGER_JOB_REQUEST_ATTACH: number
  HOST_RESOLVER_MANAGER_JOB_REQUEST_DETACH: number
  HOST_RESOLVER_MANAGER_JOB_STARTED: number
  HOST_RESOLVER_MANAGER_REQUEST: number
  HOST_RESOLVER_SYSTEM_TASK: number
  HTTP2_PROXY_CLIENT_SESSION: number
  HTTP2_SESSION: number
  HTTP2_SESSION_CLOSE: number
  HTTP2_SESSION_INITIALIZED: number
  HTTP2_SESSION_INITIAL_WINDOW_SIZE_OUT_OF_RANGE: number
  HTTP2_SESSION_PING: number
  HTTP2_SESSION_POOL_CREATED_NEW_SESSION: number
  HTTP2_SESSION_POOL_FOUND_EXISTING_SESSION: number
  HTTP2_SESSION_POOL_FOUND_EXISTING_SESSION_FROM_IP_POOL: number
  HTTP2_SESSION_POOL_IMPORTED_SESSION_FROM_SOCKET: number
  HTTP2_SESSION_POOL_REMOVE_SESSION: number
  HTTP2_SESSION_RECV_ACCEPT_CH: number
  HTTP2_SESSION_RECV_DATA: number
  HTTP2_SESSION_RECV_GOAWAY: number
  HTTP2_SESSION_RECV_HEADERS: number
  HTTP2_SESSION_RECV_INVALID_HEADER: number
  HTTP2_SESSION_RECV_PUSH_PROMISE: number
  HTTP2_SESSION_RECV_RST_STREAM: number
  HTTP2_SESSION_RECV_SETTING: number
  HTTP2_SESSION_RECV_SETTINGS: number
  HTTP2_SESSION_RECV_SETTINGS_ACK: number
  HTTP2_SESSION_RECV_WINDOW_UPDATE: number
  HTTP2_SESSION_SEND_DATA: number
  HTTP2_SESSION_SEND_GREASED_FRAME: number
  HTTP2_SESSION_SEND_HEADERS: number
  HTTP2_SESSION_SEND_RST_STREAM: number
  HTTP2_SESSION_SEND_SETTINGS: number
  HTTP2_SESSION_SEND_SETTINGS_ACK: number
  HTTP2_SESSION_SEND_WINDOW_UPDATE: number
  HTTP2_SESSION_STALLED_MAX_STREAMS: number
  HTTP2_SESSION_STREAM_STALLED_BY_SESSION_SEND_WINDOW: number
  HTTP2_SESSION_STREAM_STALLED_BY_STREAM_SEND_WINDOW: number
  HTTP2_SESSION_UPDATE_RECV_WINDOW: number
  HTTP2_SESSION_UPDATE_SEND_WINDOW: number
  HTTP2_SESSION_UPDATE_STREAMS_SEND_WINDOW_SIZE: number
  HTTP2_STREAM: number
  HTTP2_STREAM_ADOPTED_PUSH_STREAM: number
  HTTP2_STREAM_ERROR: number
  HTTP2_STREAM_FLOW_CONTROL_UNSTALLED: number
  HTTP2_STREAM_SEND_PRIORITY: number
  HTTP2_STREAM_UPDATE_RECV_WINDOW: number
  HTTP2_STREAM_UPDATE_SEND_WINDOW: number
  HTTP3_CANCEL_PUSH_RECEIVED: number
  HTTP3_DATA_FRAME_RECEIVED: number
  HTTP3_DATA_SENT: number
  HTTP3_GOAWAY_RECEIVED: number
  HTTP3_GOAWAY_SENT: number
  HTTP3_HEADERS_DECODED: number
  HTTP3_HEADERS_RECEIVED: number
  HTTP3_HEADERS_SENT: number
  HTTP3_LOCAL_CONTROL_STREAM_CREATED: number
  HTTP3_LOCAL_QPACK_DECODER_STREAM_CREATED: number
  HTTP3_LOCAL_QPACK_ENCODER_STREAM_CREATED: number
  HTTP3_MAX_PUSH_ID_RECEIVED: number
  HTTP3_MAX_PUSH_ID_SENT: number
  HTTP3_PEER_CONTROL_STREAM_CREATED: number
  HTTP3_PEER_QPACK_DECODER_STREAM_CREATED: number
  HTTP3_PEER_QPACK_ENCODER_STREAM_CREATED: number
  HTTP3_PRIORITY_UPDATE_RECEIVED: number
  HTTP3_PRIORITY_UPDATE_SENT: number
  HTTP3_PUSH_PROMISE_DECODED: number
  HTTP3_PUSH_PROMISE_RECEIVED: number
  HTTP3_PUSH_PROMISE_SENT: number
  HTTP3_SETTINGS_RECEIVED: number
  HTTP3_SETTINGS_RESUMED: number
  HTTP3_SETTINGS_SENT: number
  HTTP3_UNKNOWN_FRAME_RECEIVED: number
  HTTP_CACHE_ADD_TO_ENTRY: number
  HTTP_CACHE_CALLER_REQUEST_HEADERS: number
  HTTP_CACHE_CREATE_ENTRY: number
  HTTP_CACHE_DOOM_ENTRY: number
  HTTP_CACHE_GET_BACKEND: number
  HTTP_CACHE_OPEN_ENTRY: number
  HTTP_CACHE_OPEN_OR_CREATE_ENTRY: number
  HTTP_CACHE_READ_DATA: number
  HTTP_CACHE_READ_INFO: number
  HTTP_CACHE_RESTART_PARTIAL_REQUEST: number
  HTTP_CACHE_RE_SEND_PARTIAL_REQUEST: number
  HTTP_CACHE_WRITE_DATA: number
  HTTP_CACHE_WRITE_INFO: number
  HTTP_PROXY_CONNECT_JOB_CONNECT: number
  HTTP_SERVER_PROPERTIES_INITIALIZATION: number
  HTTP_SERVER_PROPERTIES_UPDATE_CACHE: number
  HTTP_SERVER_PROPERTIES_UPDATE_PREFS: number
  HTTP_STREAM_JOB: number
  HTTP_STREAM_JOB_BOUND_TO_QUIC_STREAM_FACTORY_JOB: number
  HTTP_STREAM_JOB_BOUND_TO_REQUEST: number
  HTTP_STREAM_JOB_CONTROLLER: number
  HTTP_STREAM_JOB_CONTROLLER_ALT_SVC_FOUND: number
  HTTP_STREAM_JOB_CONTROLLER_BOUND: number
  HTTP_STREAM_JOB_CONTROLLER_PROXY_SERVER_RESOLVED: number
  HTTP_STREAM_JOB_DELAYED: number
  HTTP_STREAM_JOB_INIT_CONNECTION: number
  HTTP_STREAM_JOB_ORPHANED: number
  HTTP_STREAM_JOB_RESUMED: number
  HTTP_STREAM_JOB_RESUME_INIT_CONNECTION: number
  HTTP_STREAM_JOB_THROTTLED: number
  HTTP_STREAM_JOB_WAITING: number
  HTTP_STREAM_PARSER_READ_HEADERS: number
  HTTP_STREAM_REQUEST: number
  HTTP_STREAM_REQUEST_BOUND_TO_JOB: number
  HTTP_STREAM_REQUEST_BOUND_TO_QUIC_SESSION: number
  HTTP_STREAM_REQUEST_PROTO: number
  HTTP_STREAM_REQUEST_STARTED_JOB: number
  HTTP_TRANSACTION_DRAIN_BODY_FOR_AUTH_RESTART: number
  HTTP_TRANSACTION_HTTP2_SEND_REQUEST_HEADERS: number
  HTTP_TRANSACTION_QUIC_SEND_REQUEST_HEADERS: number
  HTTP_TRANSACTION_READ_BODY: number
  HTTP_TRANSACTION_READ_EARLY_HINTS_RESPONSE_HEADERS: number
  HTTP_TRANSACTION_READ_HEADERS: number
  HTTP_TRANSACTION_READ_RESPONSE_HEADERS: number
  HTTP_TRANSACTION_READ_TUNNEL_RESPONSE_HEADERS: number
  HTTP_TRANSACTION_RESTART_AFTER_ERROR: number
  HTTP_TRANSACTION_RESTART_MISDIRECTED_REQUEST: number
  HTTP_TRANSACTION_SEND_REQUEST: number
  HTTP_TRANSACTION_SEND_REQUEST_BODY: number
  HTTP_TRANSACTION_SEND_REQUEST_HEADERS: number
  HTTP_TRANSACTION_SEND_TUNNEL_HEADERS: number
  HTTP_TRANSACTION_TUNNEL_READ_HEADERS: number
  HTTP_TRANSACTION_TUNNEL_SEND_REQUEST: number
  IN_MEMORY_CACHE_BYTES_READ: number
  IN_MEMORY_CACHE_READ_REQUEST_HEADERS: number
  IN_MEMORY_CACHE_READ_RESPONSE_HEADERS: number
  NETWORK_CHANGED: number
  NETWORK_CONNECTIVITY_CHANGED: number
  NETWORK_DELEGATE_BEFORE_START_TRANSACTION: number
  NETWORK_DELEGATE_BEFORE_URL_REQUEST: number
  NETWORK_DELEGATE_HEADERS_RECEIVED: number
  NETWORK_IP_ADDRESSES_CHANGED: number
  NETWORK_QUALITY_CHANGED: number
  OBLIVIOUS_HTTP_REQUEST_DATA: number
  OBLIVIOUS_HTTP_REQUEST_END: number
  OBLIVIOUS_HTTP_REQUEST_START: number
  OBLIVIOUS_HTTP_RESPONSE_DATA: number
  PAC_FILE_DECIDER: number
  PAC_FILE_DECIDER_FALLING_BACK_TO_NEXT_PAC_SOURCE: number
  PAC_FILE_DECIDER_FETCH_PAC_SCRIPT: number
  PAC_FILE_DECIDER_HAS_NO_FETCHER: number
  PAC_FILE_DECIDER_WAIT: number
  PAC_JAVASCRIPT_ALERT: number
  PAC_JAVASCRIPT_ERROR: number
  PRIVATE_NETWORK_ACCESS_CHECK: number
  PROXY_CONFIG_CHANGED: number
  PROXY_LIST_FALLBACK: number
  PROXY_RESOLUTION_SERVICE: number
  PROXY_RESOLUTION_SERVICE_DEPRIORITIZED_BAD_PROXIES: number
  PROXY_RESOLUTION_SERVICE_RESOLVED_PROXY_LIST: number
  PROXY_RESOLUTION_SERVICE_WAITING_FOR_INIT_PAC: number
  QUIC_ACCEPT_CH_FRAME_RECEIVED: number
  QUIC_CHROMIUM_CLIENT_STREAM_READ_EARLY_HINTS_RESPONSE_HEADERS: number
  QUIC_CHROMIUM_CLIENT_STREAM_READ_RESPONSE_HEADERS: number
  QUIC_CHROMIUM_CLIENT_STREAM_READ_RESPONSE_TRAILERS: number
  QUIC_CHROMIUM_CLIENT_STREAM_SEND_REQUEST_HEADERS: number
  QUIC_CONGESTION_CONTROL_CONFIGURED: number
  QUIC_CONNECTION_MIGRATION_FAILURE: number
  QUIC_CONNECTION_MIGRATION_FAILURE_AFTER_PROBING: number
  QUIC_CONNECTION_MIGRATION_MODE: number
  QUIC_CONNECTION_MIGRATION_ON_MIGRATE_BACK: number
  QUIC_CONNECTION_MIGRATION_ON_NETWORK_CONNECTED: number
  QUIC_CONNECTION_MIGRATION_ON_NETWORK_DISCONNECTED: number
  QUIC_CONNECTION_MIGRATION_ON_NETWORK_MADE_DEFAULT: number
  QUIC_CONNECTION_MIGRATION_ON_PATH_DEGRADING: number
  QUIC_CONNECTION_MIGRATION_ON_WRITE_ERROR: number
  QUIC_CONNECTION_MIGRATION_PLATFORM_NOTIFICATION: number
  QUIC_CONNECTION_MIGRATION_SUCCESS: number
  QUIC_CONNECTION_MIGRATION_SUCCESS_AFTER_PROBING: number
  QUIC_CONNECTION_MIGRATION_TRIGGERED: number
  QUIC_CONNECTIVITY_PROBING_MANAGER_CANCEL_PROBING: number
  QUIC_CONNECTIVITY_PROBING_MANAGER_PROBE_RECEIVED: number
  QUIC_CONNECTIVITY_PROBING_MANAGER_PROBE_SENT: number
  QUIC_CONNECTIVITY_PROBING_MANAGER_START_PROBING: number
  QUIC_CONNECTIVITY_PROBING_MANAGER_STATELESS_RESET_RECEIVED: number
  QUIC_FAILED_TO_VALIDATE_SERVER_PREFERRED_ADDRESS: number
  QUIC_HTTP_STREAM_ADOPTED_PUSH_STREAM: number
  QUIC_HTTP_STREAM_PUSH_PROMISE_RENDEZVOUS: number
  QUIC_ON_SERVER_PREFERRED_ADDRESS_AVAILABLE: number
  QUIC_PORT_MIGRATION_FAILURE: number
  QUIC_PORT_MIGRATION_SUCCESS: number
  QUIC_PORT_MIGRATION_TRIGGERED: number
  QUIC_READ_ERROR: number
  QUIC_SESSION: number
  QUIC_SESSION_ACK_FRAME_RECEIVED: number
  QUIC_SESSION_ACK_FRAME_SENT: number
  QUIC_SESSION_ATTEMPTING_TO_PROCESS_UNDECRYPTABLE_PACKET: number
  QUIC_SESSION_BLOCKED_FRAME_RECEIVED: number
  QUIC_SESSION_BLOCKED_FRAME_SENT: number
  QUIC_SESSION_BUFFERED_UNDECRYPTABLE_PACKET: number
  QUIC_SESSION_CERTIFICATE_VERIFIED: number
  QUIC_SESSION_CERTIFICATE_VERIFY_FAILED: number
  QUIC_SESSION_CLOSED: number
  QUIC_SESSION_CLOSE_ON_ERROR: number
  QUIC_SESSION_COALESCED_PACKET_SENT: number
  QUIC_SESSION_CONNECTION_CLOSE_FRAME_RECEIVED: number
  QUIC_SESSION_CONNECTION_CLOSE_FRAME_SENT: number
  QUIC_SESSION_CONNECTIVITY_PROBING_FINISHED: number
  QUIC_SESSION_CRYPTO_FRAME_RECEIVED: number
  QUIC_SESSION_CRYPTO_FRAME_SENT: number
  QUIC_SESSION_CRYPTO_HANDSHAKE_MESSAGE_RECEIVED: number
  QUIC_SESSION_CRYPTO_HANDSHAKE_MESSAGE_SENT: number
  QUIC_SESSION_DROPPED_UNDECRYPTABLE_PACKET: number
  QUIC_SESSION_DUPLICATE_PACKET_RECEIVED: number
  QUIC_SESSION_GOAWAY_FRAME_RECEIVED: number
  QUIC_SESSION_GOAWAY_FRAME_SENT: number
  QUIC_SESSION_HANDSHAKE_DONE_FRAME_RECEIVED: number
  QUIC_SESSION_KEY_UPDATE: number
  QUIC_SESSION_MAX_STREAMS_FRAME_RECEIVED: number
  QUIC_SESSION_MAX_STREAMS_FRAME_SENT: number
  QUIC_SESSION_MESSAGE_FRAME_RECEIVED: number
  QUIC_SESSION_MESSAGE_FRAME_SENT: number
  QUIC_SESSION_MTU_DISCOVERY_FRAME_SENT: number
  QUIC_SESSION_NEW_CONNECTION_ID_FRAME_RECEIVED: number
  QUIC_SESSION_NEW_CONNECTION_ID_FRAME_SENT: number
  QUIC_SESSION_NEW_TOKEN_FRAME_RECEIVED: number
  QUIC_SESSION_NEW_TOKEN_FRAME_SENT: number
  QUIC_SESSION_PACKET_AUTHENTICATED: number
  QUIC_SESSION_PACKET_HEADER_REVIVED: number
  QUIC_SESSION_PACKET_LOST: number
  QUIC_SESSION_PACKET_RECEIVED: number
  QUIC_SESSION_PACKET_RETRANSMITTED: number
  QUIC_SESSION_PACKET_SENT: number
  QUIC_SESSION_PADDING_FRAME_RECEIVED: number
  QUIC_SESSION_PADDING_FRAME_SENT: number
  QUIC_SESSION_PATH_CHALLENGE_FRAME_RECEIVED: number
  QUIC_SESSION_PATH_CHALLENGE_FRAME_SENT: number
  QUIC_SESSION_PATH_RESPONSE_FRAME_RECEIVED: number
  QUIC_SESSION_PATH_RESPONSE_FRAME_SENT: number
  QUIC_SESSION_PING_FRAME_RECEIVED: number
  QUIC_SESSION_PING_FRAME_SENT: number
  QUIC_SESSION_PUBLIC_RESET_PACKET_RECEIVED: number
  QUIC_SESSION_PUSH_PROMISE_RECEIVED: number
  QUIC_SESSION_RETIRE_CONNECTION_ID_FRAME_RECEIVED: number
  QUIC_SESSION_RETIRE_CONNECTION_ID_FRAME_SENT: number
  QUIC_SESSION_RST_STREAM_FRAME_RECEIVED: number
  QUIC_SESSION_RST_STREAM_FRAME_SENT: number
  QUIC_SESSION_STOP_SENDING_FRAME_RECEIVED: number
  QUIC_SESSION_STOP_SENDING_FRAME_SENT: number
  QUIC_SESSION_STOP_WAITING_FRAME_RECEIVED: number
  QUIC_SESSION_STOP_WAITING_FRAME_SENT: number
  QUIC_SESSION_STREAMS_BLOCKED_FRAME_RECEIVED: number
  QUIC_SESSION_STREAMS_BLOCKED_FRAME_SENT: number
  QUIC_SESSION_STREAM_FRAME_COALESCED: number
  QUIC_SESSION_STREAM_FRAME_RECEIVED: number
  QUIC_SESSION_STREAM_FRAME_SENT: number
  QUIC_SESSION_TRANSPORT_PARAMETERS_RECEIVED: number
  QUIC_SESSION_TRANSPORT_PARAMETERS_RESUMED: number
  QUIC_SESSION_TRANSPORT_PARAMETERS_SENT: number
  QUIC_SESSION_UNAUTHENTICATED_PACKET_HEADER_RECEIVED: number
  QUIC_SESSION_VERSION_NEGOTIATED: number
  QUIC_SESSION_VERSION_NEGOTIATION_PACKET_RECEIVED: number
  QUIC_SESSION_WEBTRANSPORT_CLIENT_ALIVE: number
  QUIC_SESSION_WEBTRANSPORT_CLIENT_STATE_CHANGED: number
  QUIC_SESSION_WINDOW_UPDATE_FRAME_RECEIVED: number
  QUIC_SESSION_WINDOW_UPDATE_FRAME_SENT: number
  QUIC_SESSION_ZERO_RTT_REJECTED: number
  QUIC_START_VALIDATING_SERVER_PREFERRED_ADDRESS: number
  QUIC_STREAM_FACTORY_JOB: number
  QUIC_STREAM_FACTORY_JOB_BOUND_TO_HTTP_STREAM_JOB: number
  QUIC_STREAM_FACTORY_JOB_CONNECT: number
  QUIC_STREAM_FACTORY_JOB_RETRY_ON_ALTERNATE_NETWORK: number
  QUIC_STREAM_FACTORY_JOB_STALE_HOST_NOT_USED_ON_CONNECTION: number
  QUIC_STREAM_FACTORY_JOB_STALE_HOST_RESOLUTION_MATCHED: number
  QUIC_STREAM_FACTORY_JOB_STALE_HOST_RESOLUTION_NO_MATCH: number
  QUIC_STREAM_FACTORY_JOB_STALE_HOST_TRIED_ON_CONNECTION: number
  QUIC_SUCCESSFULLY_MIGRATED_TO_SERVER_PREFERRED_ADDRESS: number
  REQUEST_ALIVE: number
  RESOURCE_SCHEDULER_REQUEST_STARTED: number
  SERVER_PUSH_LOOKUP_TRANSACTION: number
  SIGNED_CERTIFICATE_TIMESTAMPS_CHECKED: number
  SIGNED_CERTIFICATE_TIMESTAMPS_RECEIVED: number
  SIMPLE_CACHE_ENTRY: number
  SIMPLE_CACHE_ENTRY_CHECKSUM_BEGIN: number
  SIMPLE_CACHE_ENTRY_CHECKSUM_END: number
  SIMPLE_CACHE_ENTRY_CLOSE_BEGIN: number
  SIMPLE_CACHE_ENTRY_CLOSE_CALL: number
  SIMPLE_CACHE_ENTRY_CLOSE_END: number
  SIMPLE_CACHE_ENTRY_CREATE_BEGIN: number
  SIMPLE_CACHE_ENTRY_CREATE_CALL: number
  SIMPLE_CACHE_ENTRY_CREATE_END: number
  SIMPLE_CACHE_ENTRY_CREATE_OPTIMISTIC: number
  SIMPLE_CACHE_ENTRY_DOOM_BEGIN: number
  SIMPLE_CACHE_ENTRY_DOOM_CALL: number
  SIMPLE_CACHE_ENTRY_DOOM_END: number
  SIMPLE_CACHE_ENTRY_OPEN_BEGIN: number
  SIMPLE_CACHE_ENTRY_OPEN_CALL: number
  SIMPLE_CACHE_ENTRY_OPEN_END: number
  SIMPLE_CACHE_ENTRY_OPEN_OR_CREATE_BEGIN: number
  SIMPLE_CACHE_ENTRY_OPEN_OR_CREATE_CALL: number
  SIMPLE_CACHE_ENTRY_OPEN_OR_CREATE_END: number
  SIMPLE_CACHE_ENTRY_READ_BEGIN: number
  SIMPLE_CACHE_ENTRY_READ_CALL: number
  SIMPLE_CACHE_ENTRY_READ_END: number
  SIMPLE_CACHE_ENTRY_READ_SPARSE_BEGIN: number
  SIMPLE_CACHE_ENTRY_READ_SPARSE_CALL: number
  SIMPLE_CACHE_ENTRY_READ_SPARSE_END: number
  SIMPLE_CACHE_ENTRY_SET_KEY: number
  SIMPLE_CACHE_ENTRY_WRITE_BEGIN: number
  SIMPLE_CACHE_ENTRY_WRITE_CALL: number
  SIMPLE_CACHE_ENTRY_WRITE_END: number
  SIMPLE_CACHE_ENTRY_WRITE_OPTIMISTIC: number
  SIMPLE_CACHE_ENTRY_WRITE_SPARSE_BEGIN: number
  SIMPLE_CACHE_ENTRY_WRITE_SPARSE_CALL: number
  SIMPLE_CACHE_ENTRY_WRITE_SPARSE_END: number
  SOCKET_ALIVE: number
  SOCKET_BYTES_RECEIVED: number
  SOCKET_BYTES_SENT: number
  SOCKET_CLOSED: number
  SOCKET_IN_USE: number
  SOCKET_POOL: number
  SOCKET_POOL_BOUND_TO_CONNECT_JOB: number
  SOCKET_POOL_BOUND_TO_SOCKET: number
  SOCKET_POOL_CLOSING_SOCKET: number
  SOCKET_POOL_CONNECTING_N_SOCKETS: number
  SOCKET_POOL_CONNECT_JOB_CREATED: number
  SOCKET_POOL_REUSED_AN_EXISTING_SOCKET: number
  SOCKET_POOL_STALLED_MAX_SOCKETS: number
  SOCKET_POOL_STALLED_MAX_SOCKETS_PER_GROUP: number
  SOCKET_READ_ERROR: number
  SOCKET_WRITE_ERROR: number
  SOCKS5_CONNECT: number
  SOCKS5_GREET_READ: number
  SOCKS5_GREET_WRITE: number
  SOCKS5_HANDSHAKE_READ: number
  SOCKS5_HANDSHAKE_WRITE: number
  SOCKS_CONNECT: number
  SOCKS_CONNECT_JOB_CONNECT: number
  SOCKS_HOSTNAME_TOO_BIG: number
  SOCKS_SERVER_ERROR: number
  SOCKS_UNEXPECTEDLY_CLOSED_DURING_GREETING: number
  SOCKS_UNEXPECTEDLY_CLOSED_DURING_HANDSHAKE: number
  SOCKS_UNEXPECTED_AUTH: number
  SOCKS_UNEXPECTED_VERSION: number
  SOCKS_UNKNOWN_ADDRESS_TYPE: number
  SPARSE_DELETE_CHILDREN: number
  SPARSE_GET_RANGE: number
  SPARSE_READ: number
  SPARSE_READ_CHILD_DATA: number
  SPARSE_WRITE: number
  SPARSE_WRITE_CHILD_DATA: number
  SPECIFIC_NETWORK_CONNECTED: number
  SPECIFIC_NETWORK_DISCONNECTED: number
  SPECIFIC_NETWORK_MADE_DEFAULT: number
  SPECIFIC_NETWORK_SOON_TO_DISCONNECT: number
  SSL_ALERT_RECEIVED: number
  SSL_ALERT_SENT: number
  SSL_CERTIFICATES_RECEIVED: number
  SSL_CLIENT_CERT_PROVIDED: number
  SSL_CLIENT_CERT_REQUESTED: number
  SSL_CONFIRM_HANDSHAKE: number
  SSL_CONNECT: number
  SSL_CONNECT_JOB_CONNECT: number
  SSL_CONNECT_JOB_RESTART_WITH_ECH_CONFIG_LIST: number
  SSL_ECH_CONFIG_LIST: number
  SSL_ENCYPTED_CLIENT_HELLO: number
  SSL_HANDSHAKE_ERROR: number
  SSL_HANDSHAKE_MESSAGE_RECEIVED: number
  SSL_HANDSHAKE_MESSAGE_SENT: number
  SSL_PRIVATE_KEY_OP: number
  SSL_READ_ERROR: number
  SSL_SERVER_HANDSHAKE: number
  SSL_SOCKET_BYTES_RECEIVED: number
  SSL_SOCKET_BYTES_SENT: number
  SSL_VERIFICATION_MERGED: number
  SSL_WRITE_ERROR: number
  SUBMITTED_TO_RESOLVER_THREAD: number
  TCP_ACCEPT: number
  TCP_CLIENT_SOCKET_POOL_REQUESTED_SOCKET: number
  TCP_CLIENT_SOCKET_POOL_REQUESTED_SOCKETS: number
  TCP_CONNECT: number
  TCP_CONNECT_ATTEMPT: number
  THROTTLING_DISABLED_FOR_HOST: number
  THROTTLING_REJECTED_REQUEST: number
  TRANSPORT_CONNECT_JOB_CONNECT: number
  TRANSPORT_CONNECT_JOB_CONNECT_ATTEMPT: number
  TRANSPORT_CONNECT_JOB_IPV6_FALLBACK: number
  TRANSPORT_SECURITY_STATE_SHOULD_UPGRADE_TO_SSL: number
  TRIAL_CERT_VERIFIER_JOB: number
  TRIAL_CERT_VERIFIER_JOB_COMPARISON_STARTED: number
  TRUST_TOKEN_OPERATION_BEGIN_ISSUANCE: number
  TRUST_TOKEN_OPERATION_BEGIN_REDEMPTION: number
  TRUST_TOKEN_OPERATION_BEGIN_SIGNING: number
  TRUST_TOKEN_OPERATION_FINALIZE_ISSUANCE: number
  TRUST_TOKEN_OPERATION_FINALIZE_REDEMPTION: number
  TRUST_TOKEN_OPERATION_REQUESTED: number
  UDP_BYTES_RECEIVED: number
  UDP_BYTES_SENT: number
  UDP_CONNECT: number
  UDP_LOCAL_ADDRESS: number
  UDP_RECEIVE_ERROR: number
  UDP_SEND_ERROR: number
  UPLOAD_DATA_STREAM_INIT: number
  UPLOAD_DATA_STREAM_READ: number
  URL_REQUEST_DELEGATE_CERTIFICATE_REQUESTED: number
  URL_REQUEST_DELEGATE_CONNECTED: number
  URL_REQUEST_DELEGATE_RECEIVED_REDIRECT: number
  URL_REQUEST_DELEGATE_RESPONSE_STARTED: number
  URL_REQUEST_DELEGATE_SSL_CERTIFICATE_ERROR: number
  URL_REQUEST_FAKE_RESPONSE_HEADERS_CREATED: number
  URL_REQUEST_FILTERS_SET: number
  URL_REQUEST_JOB_BYTES_READ: number
  URL_REQUEST_JOB_FILTERED_BYTES_READ: number
  URL_REQUEST_REDIRECTED: number
  URL_REQUEST_REDIRECT_JOB: number
  URL_REQUEST_SET_PRIORITY: number
  URL_REQUEST_START_JOB: number
  WAITING_FOR_PROXY_RESOLVER_THREAD: number
  WEBSOCKET_CLOSE_TIMEOUT: number
  WEBSOCKET_INVALID_FRAME: number
  WEBSOCKET_READ_BUFFER_SIZE_CHANGED: number
  WEBSOCKET_RECV_FRAME_HEADER: number
  WEBSOCKET_SENT_FRAME_HEADER: number
  WEBSOCKET_UPGRADE_FAILURE: number
  WPAD_DHCP_WIN_FETCH: number
  WPAD_DHCP_WIN_GET_ADAPTERS: number
  WPAD_DHCP_WIN_ON_FETCHER_DONE: number
  WPAD_DHCP_WIN_ON_WAIT_TIMER: number
  WPAD_DHCP_WIN_START_WAIT_TIMER: number
}

interface LogSourceType {
  BIDIRECTIONAL_STREAM: number
  CERT_VERIFIER_JOB: number
  CERT_VERIFIER_TASK: number
  COOKIE_STORE: number
  CT_TREE_STATE_TRACKER: number
  DISK_CACHE_ENTRY: number
  EXPONENTIAL_BACKOFF_THROTTLING: number
  HOST_CACHE_PERSISTENCE_MANAGER: number
  HOST_RESOLVER_IMPL_JOB: number
  HTTP2_SESSION: number
  HTTP3_SESSION: number
  HTTP_AUTH_CONTROLLER: number
  HTTP_PROXY_CONNECT_JOB: number
  HTTP_SERVER_PROPERTIES: number
  HTTP_STREAM_JOB: number
  HTTP_STREAM_JOB_CONTROLLER: number
  MEMORY_CACHE_ENTRY: number
  NETWORK_QUALITY_ESTIMATOR: number
  NETWORK_SERVICE_HOST_RESOLVER: number
  NONE: number
  PAC_FILE_DECIDER: number
  PROXY_CLIENT_SOCKET: number
  QUIC_CONNECTION_MIGRATION: number
  QUIC_SESSION: number
  QUIC_STREAM_FACTORY_JOB: number
  SERVER_PUSH_LOOKUP_TRANSACTION: number
  SOCKET: number
  SOCKS_CONNECT_JOB: number
  SSL_CONNECT_JOB: number
  TRANSPORT_CONNECT_JOB: number
  TRIAL_CERT_VERIFIER_JOB: number
  UDP_SOCKET: number
  URL_REQUEST: number
  WEB_TRANSPORT_CLIENT: number
}

interface NetError {
  ERR_ABORTED: number
  ERR_ACCESS_DENIED: number
  ERR_ADDRESS_INVALID: number
  ERR_ADDRESS_IN_USE: number
  ERR_ADDRESS_UNREACHABLE: number
  ERR_ADD_USER_CERT_FAILED: number
  ERR_ALPN_NEGOTIATION_FAILED: number
  ERR_BAD_SSL_CLIENT_AUTH_CERT: number
  ERR_BLOCKED_BY_ADMINISTRATOR: number
  ERR_BLOCKED_BY_CLIENT: number
  ERR_BLOCKED_BY_CSP: number
  ERR_BLOCKED_BY_ORB: number
  ERR_BLOCKED_BY_RESPONSE: number
  ERR_CACHED_IP_ADDRESS_SPACE_BLOCKED_BY_PRIVATE_NETWORK_ACCESS_POLICY: number
  ERR_CACHE_AUTH_FAILURE_AFTER_READ: number
  ERR_CACHE_CHECKSUM_MISMATCH: number
  ERR_CACHE_CHECKSUM_READ_FAILURE: number
  ERR_CACHE_CREATE_FAILURE: number
  ERR_CACHE_DOOM_FAILURE: number
  ERR_CACHE_ENTRY_NOT_SUITABLE: number
  ERR_CACHE_LOCK_TIMEOUT: number
  ERR_CACHE_MISS: number
  ERR_CACHE_OPEN_FAILURE: number
  ERR_CACHE_OPEN_OR_CREATE_FAILURE: number
  ERR_CACHE_OPERATION_NOT_SUPPORTED: number
  ERR_CACHE_RACE: number
  ERR_CACHE_READ_FAILURE: number
  ERR_CACHE_WRITE_FAILURE: number
  ERR_CERTIFICATE_TRANSPARENCY_REQUIRED: number
  ERR_CERT_AUTHORITY_INVALID: number
  ERR_CERT_COMMON_NAME_INVALID: number
  ERR_CERT_CONTAINS_ERRORS: number
  ERR_CERT_DATABASE_CHANGED: number
  ERR_CERT_DATE_INVALID: number
  ERR_CERT_END: number
  ERR_CERT_INVALID: number
  ERR_CERT_KNOWN_INTERCEPTION_BLOCKED: number
  ERR_CERT_NAME_CONSTRAINT_VIOLATION: number
  ERR_CERT_NON_UNIQUE_NAME: number
  ERR_CERT_NO_REVOCATION_MECHANISM: number
  ERR_CERT_REVOKED: number
  ERR_CERT_SYMANTEC_LEGACY: number
  ERR_CERT_UNABLE_TO_CHECK_REVOCATION: number
  ERR_CERT_VALIDITY_TOO_LONG: number
  ERR_CERT_WEAK_KEY: number
  ERR_CERT_WEAK_SIGNATURE_ALGORITHM: number
  ERR_CLEARTEXT_NOT_PERMITTED: number
  ERR_CLIENT_AUTH_CERT_TYPE_UNSUPPORTED: number
  ERR_CONNECTION_ABORTED: number
  ERR_CONNECTION_CLOSED: number
  ERR_CONNECTION_FAILED: number
  ERR_CONNECTION_REFUSED: number
  ERR_CONNECTION_RESET: number
  ERR_CONNECTION_TIMED_OUT: number
  ERR_CONTENT_DECODING_FAILED: number
  ERR_CONTENT_DECODING_INIT_FAILED: number
  ERR_CONTENT_LENGTH_MISMATCH: number
  ERR_CONTEXT_SHUT_DOWN: number
  ERR_CT_CONSISTENCY_PROOF_PARSING_FAILED: number
  ERR_CT_STH_INCOMPLETE: number
  ERR_CT_STH_PARSING_FAILED: number
  ERR_DISALLOWED_URL_SCHEME: number
  ERR_DNS_CACHE_MISS: number
  ERR_DNS_MALFORMED_RESPONSE: number
  ERR_DNS_NAME_HTTPS_ONLY: number
  ERR_DNS_NO_MATCHING_SUPPORTED_ALPN: number
  ERR_DNS_REQUEST_CANCELLED: number
  ERR_DNS_SEARCH_EMPTY: number
  ERR_DNS_SECURE_RESOLVER_HOSTNAME_RESOLUTION_FAILED: number
  ERR_DNS_SERVER_FAILED: number
  ERR_DNS_SERVER_REQUIRES_TCP: number
  ERR_DNS_SORT_ERROR: number
  ERR_DNS_TIMED_OUT: number
  ERR_EARLY_DATA_REJECTED: number
  ERR_ECH_FALLBACK_CERTIFICATE_INVALID: number
  ERR_ECH_NOT_NEGOTIATED: number
  ERR_EMPTY_RESPONSE: number
  ERR_ENCODING_CONVERSION_FAILED: number
  ERR_ENCODING_DETECTION_FAILED: number
  ERR_FAILED: number
  ERR_FILE_EXISTS: number
  ERR_FILE_NOT_FOUND: number
  ERR_FILE_NO_SPACE: number
  ERR_FILE_PATH_TOO_LONG: number
  ERR_FILE_TOO_BIG: number
  ERR_FILE_VIRUS_INFECTED: number
  ERR_FTP_BAD_COMMAND_SEQUENCE: number
  ERR_FTP_COMMAND_NOT_SUPPORTED: number
  ERR_FTP_FAILED: number
  ERR_FTP_FILE_BUSY: number
  ERR_FTP_SERVICE_UNAVAILABLE: number
  ERR_FTP_SYNTAX_ERROR: number
  ERR_FTP_TRANSFER_ABORTED: number
  ERR_H2_OR_QUIC_REQUIRED: number
  ERR_HOST_RESOLVER_QUEUE_TOO_LARGE: number
  ERR_HTTP2_CLAIMED_PUSHED_STREAM_RESET_BY_SERVER: number
  ERR_HTTP2_CLIENT_REFUSED_STREAM: number
  ERR_HTTP2_COMPRESSION_ERROR: number
  ERR_HTTP2_FLOW_CONTROL_ERROR: number
  ERR_HTTP2_FRAME_SIZE_ERROR: number
  ERR_HTTP2_INADEQUATE_TRANSPORT_SECURITY: number
  ERR_HTTP2_PING_FAILED: number
  ERR_HTTP2_PROTOCOL_ERROR: number
  ERR_HTTP2_PUSHED_RESPONSE_DOES_NOT_MATCH: number
  ERR_HTTP2_PUSHED_STREAM_NOT_AVAILABLE: number
  ERR_HTTP2_RST_STREAM_NO_ERROR_RECEIVED: number
  ERR_HTTP2_SERVER_REFUSED_STREAM: number
  ERR_HTTP2_STREAM_CLOSED: number
  ERR_HTTPS_PROXY_TUNNEL_RESPONSE_REDIRECT: number
  ERR_HTTP_1_1_REQUIRED: number
  ERR_HTTP_RESPONSE_CODE_FAILURE: number
  ERR_ICANN_NAME_COLLISION: number
  ERR_IMPORT_CA_CERT_FAILED: number
  ERR_IMPORT_CA_CERT_NOT_CA: number
  ERR_IMPORT_CERT_ALREADY_EXISTS: number
  ERR_IMPORT_SERVER_CERT_FAILED: number
  ERR_INCOMPLETE_CHUNKED_ENCODING: number
  ERR_INCOMPLETE_HTTP2_HEADERS: number
  ERR_INCONSISTENT_IP_ADDRESS_SPACE: number
  ERR_INSECURE_RESPONSE: number
  ERR_INSUFFICIENT_RESOURCES: number
  ERR_INTERNET_DISCONNECTED: number
  ERR_INVALID_ARGUMENT: number
  ERR_INVALID_AUTH_CREDENTIALS: number
  ERR_INVALID_CHUNKED_ENCODING: number
  ERR_INVALID_ECH_CONFIG_LIST: number
  ERR_INVALID_HANDLE: number
  ERR_INVALID_HTTP_RESPONSE: number
  ERR_INVALID_REDIRECT: number
  ERR_INVALID_RESPONSE: number
  ERR_INVALID_SIGNED_EXCHANGE: number
  ERR_INVALID_URL: number
  ERR_INVALID_WEB_BUNDLE: number
  ERR_IO_PENDING: number
  ERR_KEY_GENERATION_FAILED: number
  ERR_MALFORMED_IDENTITY: number
  ERR_MANDATORY_PROXY_CONFIGURATION_FAILED: number
  ERR_METHOD_NOT_SUPPORTED: number
  ERR_MISCONFIGURED_AUTH_ENVIRONMENT: number
  ERR_MISSING_AUTH_CREDENTIALS: number
  ERR_MSG_TOO_BIG: number
  ERR_NAME_NOT_RESOLVED: number
  ERR_NAME_RESOLUTION_FAILED: number
  ERR_NETWORK_ACCESS_DENIED: number
  ERR_NETWORK_CHANGED: number
  ERR_NETWORK_IO_SUSPENDED: number
  ERR_NOT_IMPLEMENTED: number
  ERR_NO_BUFFER_SPACE: number
  ERR_NO_PRIVATE_KEY_FOR_CERT: number
  ERR_NO_SSL_VERSIONS_ENABLED: number
  ERR_NO_SUPPORTED_PROXIES: number
  ERR_OUT_OF_MEMORY: number
  ERR_PAC_NOT_IN_DHCP: number
  ERR_PAC_SCRIPT_FAILED: number
  ERR_PAC_SCRIPT_TERMINATED: number
  ERR_PKCS12_IMPORT_BAD_PASSWORD: number
  ERR_PKCS12_IMPORT_FAILED: number
  ERR_PKCS12_IMPORT_INVALID_FILE: number
  ERR_PKCS12_IMPORT_INVALID_MAC: number
  ERR_PKCS12_IMPORT_UNSUPPORTED: number
  ERR_PRECONNECT_MAX_SOCKET_LIMIT: number
  ERR_PRIVATE_KEY_EXPORT_FAILED: number
  ERR_PROXY_AUTH_REQUESTED: number
  ERR_PROXY_AUTH_REQUESTED_WITH_NO_CONNECTION: number
  ERR_PROXY_AUTH_UNSUPPORTED: number
  ERR_PROXY_CERTIFICATE_INVALID: number
  ERR_PROXY_CONNECTION_FAILED: number
  ERR_PROXY_HTTP_1_1_REQUIRED: number
  ERR_QUIC_CERT_ROOT_NOT_KNOWN: number
  ERR_QUIC_GOAWAY_REQUEST_CAN_BE_RETRIED: number
  ERR_QUIC_HANDSHAKE_FAILED: number
  ERR_QUIC_PROTOCOL_ERROR: number
  ERR_READ_IF_READY_NOT_IMPLEMENTED: number
  ERR_REQUEST_RANGE_NOT_SATISFIABLE: number
  ERR_RESPONSE_BODY_TOO_BIG_TO_DRAIN: number
  ERR_RESPONSE_HEADERS_MULTIPLE_CONTENT_DISPOSITION: number
  ERR_RESPONSE_HEADERS_MULTIPLE_CONTENT_LENGTH: number
  ERR_RESPONSE_HEADERS_MULTIPLE_LOCATION: number
  ERR_RESPONSE_HEADERS_TOO_BIG: number
  ERR_RESPONSE_HEADERS_TRUNCATED: number
  ERR_SELF_SIGNED_CERT_GENERATION_FAILED: number
  ERR_SOCKET_IS_CONNECTED: number
  ERR_SOCKET_NOT_CONNECTED: number
  ERR_SOCKET_RECEIVE_BUFFER_SIZE_UNCHANGEABLE: number
  ERR_SOCKET_SEND_BUFFER_SIZE_UNCHANGEABLE: number
  ERR_SOCKET_SET_RECEIVE_BUFFER_SIZE_ERROR: number
  ERR_SOCKET_SET_SEND_BUFFER_SIZE_ERROR: number
  ERR_SOCKS_CONNECTION_FAILED: number
  ERR_SOCKS_CONNECTION_HOST_UNREACHABLE: number
  ERR_SSL_BAD_PEER_PUBLIC_KEY: number
  ERR_SSL_BAD_RECORD_MAC_ALERT: number
  ERR_SSL_CLIENT_AUTH_CERT_BAD_FORMAT: number
  ERR_SSL_CLIENT_AUTH_CERT_NEEDED: number
  ERR_SSL_CLIENT_AUTH_CERT_NO_PRIVATE_KEY: number
  ERR_SSL_CLIENT_AUTH_NO_COMMON_ALGORITHMS: number
  ERR_SSL_CLIENT_AUTH_PRIVATE_KEY_ACCESS_DENIED: number
  ERR_SSL_CLIENT_AUTH_SIGNATURE_FAILED: number
  ERR_SSL_DECOMPRESSION_FAILURE_ALERT: number
  ERR_SSL_DECRYPT_ERROR_ALERT: number
  ERR_SSL_HANDSHAKE_NOT_COMPLETED: number
  ERR_SSL_KEY_USAGE_INCOMPATIBLE: number
  ERR_SSL_NO_RENEGOTIATION: number
  ERR_SSL_OBSOLETE_CIPHER: number
  ERR_SSL_PINNED_KEY_NOT_IN_CERT_CHAIN: number
  ERR_SSL_PROTOCOL_ERROR: number
  ERR_SSL_RENEGOTIATION_REQUESTED: number
  ERR_SSL_SERVER_CERT_BAD_FORMAT: number
  ERR_SSL_SERVER_CERT_CHANGED: number
  ERR_SSL_UNRECOGNIZED_NAME_ALERT: number
  ERR_SSL_VERSION_OR_CIPHER_MISMATCH: number
  ERR_SYN_REPLY_NOT_RECEIVED: number
  ERR_TEMPORARILY_THROTTLED: number
  ERR_TIMED_OUT: number
  ERR_TLS13_DOWNGRADE_DETECTED: number
  ERR_TOO_MANY_ACCEPT_CH_RESTARTS: number
  ERR_TOO_MANY_REDIRECTS: number
  ERR_TOO_MANY_RETRIES: number
  ERR_TRUST_TOKEN_OPERATION_FAILED: number
  ERR_TRUST_TOKEN_OPERATION_SUCCESS_WITHOUT_SENDING_REQUEST: number
  ERR_TUNNEL_CONNECTION_FAILED: number
  ERR_UNABLE_TO_REUSE_CONNECTION_FOR_PROXY_AUTH: number
  ERR_UNDOCUMENTED_SECURITY_LIBRARY_STATUS: number
  ERR_UNEXPECTED: number
  ERR_UNEXPECTED_PROXY_AUTH: number
  ERR_UNEXPECTED_SECURITY_LIBRARY_STATUS: number
  ERR_UNKNOWN_URL_SCHEME: number
  ERR_UNRECOGNIZED_FTP_DIRECTORY_LISTING_FORMAT: number
  ERR_UNSAFE_PORT: number
  ERR_UNSAFE_REDIRECT: number
  ERR_UNSUPPORTED_AUTH_SCHEME: number
  ERR_UPLOAD_FILE_CHANGED: number
  ERR_UPLOAD_STREAM_REWIND_NOT_SUPPORTED: number
  ERR_WINSOCK_UNEXPECTED_WRITTEN_BYTES: number
  ERR_WRONG_VERSION_ON_EARLY_DATA: number
  ERR_WS_PROTOCOL_ERROR: number
  ERR_WS_THROTTLE_QUEUE_TOO_LARGE: number
  ERR_WS_UPGRADE: number
}

interface QuicError {
  IETF_QUIC_PROTOCOL_VIOLATION: number
  INVALID_ERROR_CODE: number
  QUIC_AEAD_LIMIT_REACHED: number
  QUIC_ATTEMPT_TO_SEND_UNENCRYPTED_STREAM_DATA: number
  QUIC_BAD_MULTIPATH_FLAG: number
  QUIC_BAD_PACKET_LOSS_RATE: number
  QUIC_CONNECTION_CANCELLED: number
  QUIC_CONNECTION_ID_LIMIT_ERROR: number
  QUIC_CONNECTION_IP_POOLED: number
  QUIC_CONNECTION_MIGRATION_DISABLED_BY_CONFIG: number
  QUIC_CONNECTION_MIGRATION_HANDSHAKE_UNCONFIRMED: number
  QUIC_CONNECTION_MIGRATION_INTERNAL_ERROR: number
  QUIC_CONNECTION_MIGRATION_NON_MIGRATABLE_STREAM: number
  QUIC_CONNECTION_MIGRATION_NO_MIGRATABLE_STREAMS: number
  QUIC_CONNECTION_MIGRATION_NO_NEW_NETWORK: number
  QUIC_CONNECTION_MIGRATION_TOO_MANY_CHANGES: number
  QUIC_CRYPTO_CHLO_TOO_LARGE: number
  QUIC_CRYPTO_DUPLICATE_TAG: number
  QUIC_CRYPTO_ENCRYPTION_LEVEL_INCORRECT: number
  QUIC_CRYPTO_INTERNAL_ERROR: number
  QUIC_CRYPTO_INVALID_VALUE_LENGTH: number
  QUIC_CRYPTO_MESSAGE_AFTER_HANDSHAKE_COMPLETE: number
  QUIC_CRYPTO_MESSAGE_INDEX_NOT_FOUND: number
  QUIC_CRYPTO_MESSAGE_PARAMETER_NOT_FOUND: number
  QUIC_CRYPTO_MESSAGE_PARAMETER_NO_OVERLAP: number
  QUIC_CRYPTO_MESSAGE_WHILE_VALIDATING_CLIENT_HELLO: number
  QUIC_CRYPTO_NO_SUPPORT: number
  QUIC_CRYPTO_SERVER_CONFIG_EXPIRED: number
  QUIC_CRYPTO_SYMMETRIC_KEY_SETUP_FAILED: number
  QUIC_CRYPTO_TAGS_OUT_OF_ORDER: number
  QUIC_CRYPTO_TOO_MANY_ENTRIES: number
  QUIC_CRYPTO_TOO_MANY_REJECTS: number
  QUIC_CRYPTO_UPDATE_BEFORE_HANDSHAKE_COMPLETE: number
  QUIC_CRYPTO_VERSION_NOT_SUPPORTED: number
  QUIC_DATA_RECEIVED_ON_WRITE_UNIDIRECTIONAL_STREAM: number
  QUIC_DECOMPRESSION_FAILURE: number
  QUIC_DECRYPTION_FAILURE: number
  QUIC_EMPTY_STREAM_FRAME_NO_FIN: number
  QUIC_ENCRYPTION_FAILURE: number
  QUIC_ERROR_MIGRATING_ADDRESS: number
  QUIC_ERROR_MIGRATING_PORT: number
  QUIC_FAILED_TO_SERIALIZE_PACKET: number
  QUIC_FLOW_CONTROL_INVALID_WINDOW: number
  QUIC_FLOW_CONTROL_RECEIVED_TOO_MUCH_DATA: number
  QUIC_FLOW_CONTROL_SENT_TOO_MUCH_DATA: number
  QUIC_HANDSHAKE_FAILED: number
  QUIC_HANDSHAKE_TIMEOUT: number
  QUIC_HEADERS_STREAM_DATA_DECOMPRESS_FAILURE: number
  QUIC_HPACK_COMPRESSED_HEADER_SIZE_EXCEEDS_LIMIT: number
  QUIC_HPACK_DYNAMIC_TABLE_SIZE_UPDATE_NOT_ALLOWED: number
  QUIC_HPACK_FRAGMENT_TOO_LONG: number
  QUIC_HPACK_INDEX_VARINT_ERROR: number
  QUIC_HPACK_INITIAL_TABLE_SIZE_UPDATE_IS_ABOVE_LOW_WATER_MARK: number
  QUIC_HPACK_INVALID_INDEX: number
  QUIC_HPACK_INVALID_NAME_INDEX: number
  QUIC_HPACK_MISSING_DYNAMIC_TABLE_SIZE_UPDATE: number
  QUIC_HPACK_NAME_HUFFMAN_ERROR: number
  QUIC_HPACK_NAME_LENGTH_VARINT_ERROR: number
  QUIC_HPACK_NAME_TOO_LONG: number
  QUIC_HPACK_TABLE_SIZE_UPDATE_IS_ABOVE_ACKNOWLEDGED_SETTING: number
  QUIC_HPACK_TRUNCATED_BLOCK: number
  QUIC_HPACK_VALUE_HUFFMAN_ERROR: number
  QUIC_HPACK_VALUE_LENGTH_VARINT_ERROR: number
  QUIC_HPACK_VALUE_TOO_LONG: number
  QUIC_HTTP_CLOSED_CRITICAL_STREAM: number
  QUIC_HTTP_DECODER_ERROR: number
  QUIC_HTTP_DUPLICATE_SETTING_IDENTIFIER: number
  QUIC_HTTP_DUPLICATE_UNIDIRECTIONAL_STREAM: number
  QUIC_HTTP_FRAME_ERROR: number
  QUIC_HTTP_FRAME_TOO_LARGE: number
  QUIC_HTTP_FRAME_UNEXPECTED_ON_CONTROL_STREAM: number
  QUIC_HTTP_FRAME_UNEXPECTED_ON_SPDY_STREAM: number
  QUIC_HTTP_GOAWAY_ID_LARGER_THAN_PREVIOUS: number
  QUIC_HTTP_GOAWAY_INVALID_STREAM_ID: number
  QUIC_HTTP_INVALID_FRAME_SEQUENCE_ON_CONTROL_STREAM: number
  QUIC_HTTP_INVALID_FRAME_SEQUENCE_ON_SPDY_STREAM: number
  QUIC_HTTP_INVALID_MAX_PUSH_ID: number
  QUIC_HTTP_INVALID_SETTING_VALUE: number
  QUIC_HTTP_MISSING_SETTINGS_FRAME: number
  QUIC_HTTP_RECEIVE_SERVER_PUSH: number
  QUIC_HTTP_RECEIVE_SPDY_FRAME: number
  QUIC_HTTP_RECEIVE_SPDY_SETTING: number
  QUIC_HTTP_SERVER_INITIATED_BIDIRECTIONAL_STREAM: number
  QUIC_HTTP_STREAM_LIMIT_TOO_LOW: number
  QUIC_HTTP_STREAM_WRONG_DIRECTION: number
  QUIC_HTTP_ZERO_RTT_REJECTION_SETTINGS_MISMATCH: number
  QUIC_HTTP_ZERO_RTT_RESUMPTION_SETTINGS_MISMATCH: number
  QUIC_IETF_GQUIC_ERROR_MISSING: number
  QUIC_INTERNAL_ERROR: number
  QUIC_INVALID_0RTT_PACKET_NUMBER_OUT_OF_ORDER: number
  QUIC_INVALID_ACK_DATA: number
  QUIC_INVALID_BLOCKED_DATA: number
  QUIC_INVALID_CHANNEL_ID_SIGNATURE: number
  QUIC_INVALID_CHARACTER_IN_FIELD_VALUE: number
  QUIC_INVALID_CONNECTION_CLOSE_DATA: number
  QUIC_INVALID_CRYPTO_MESSAGE_PARAMETER: number
  QUIC_INVALID_CRYPTO_MESSAGE_TYPE: number
  QUIC_INVALID_FEC_DATA: number
  QUIC_INVALID_FRAME_DATA: number
  QUIC_INVALID_GOAWAY_DATA: number
  QUIC_INVALID_HEADERS_STREAM_DATA: number
  QUIC_INVALID_HEADER_ID: number
  QUIC_INVALID_MAX_DATA_FRAME_DATA: number
  QUIC_INVALID_MAX_STREAM_DATA_FRAME_DATA: number
  QUIC_INVALID_MESSAGE_DATA: number
  QUIC_INVALID_NEGOTIATED_VALUE: number
  QUIC_INVALID_NEW_CONNECTION_ID_DATA: number
  QUIC_INVALID_NEW_TOKEN: number
  QUIC_INVALID_PACKET_HEADER: number
  QUIC_INVALID_PATH_CHALLENGE_DATA: number
  QUIC_INVALID_PATH_CLOSE_DATA: number
  QUIC_INVALID_PATH_RESPONSE_DATA: number
  QUIC_INVALID_PRIORITY: number
  QUIC_INVALID_PRIORITY_UPDATE: number
  QUIC_INVALID_PUBLIC_RST_PACKET: number
  QUIC_INVALID_RETIRE_CONNECTION_ID_DATA: number
  QUIC_INVALID_RST_STREAM_DATA: number
  QUIC_INVALID_STOP_SENDING_FRAME_DATA: number
  QUIC_INVALID_STOP_WAITING_DATA: number
  QUIC_INVALID_STREAM_BLOCKED_DATA: number
  QUIC_INVALID_STREAM_DATA: number
  QUIC_INVALID_STREAM_ID: number
  QUIC_INVALID_VERSION: number
  QUIC_INVALID_VERSION_NEGOTIATION_PACKET: number
  QUIC_INVALID_WINDOW_UPDATE_DATA: number
  QUIC_IP_ADDRESS_CHANGED: number
  QUIC_KEY_UPDATE_ERROR: number
  QUIC_MAX_AGE_TIMEOUT: number
  QUIC_MAX_STREAMS_DATA: number
  QUIC_MAX_STREAMS_ERROR: number
  QUIC_MAYBE_CORRUPTED_MEMORY: number
  QUIC_MISSING_PAYLOAD: number
  QUIC_MISSING_WRITE_KEYS: number
  QUIC_MULTIPATH_PATH_DOES_NOT_EXIST: number
  QUIC_MULTIPATH_PATH_NOT_ACTIVE: number
  QUIC_NETWORK_IDLE_TIMEOUT: number
  QUIC_NO_ERROR: number
  QUIC_OVERLAPPING_STREAM_DATA: number
  QUIC_PACKET_READ_ERROR: number
  QUIC_PACKET_TOO_LARGE: number
  QUIC_PACKET_WRITE_ERROR: number
  QUIC_PACKET_WRONG_VERSION: number
  QUIC_PEER_GOING_AWAY: number
  QUIC_PEER_PORT_CHANGE_HANDSHAKE_UNCONFIRMED: number
  QUIC_PROOF_INVALID: number
  QUIC_PUBLIC_RESET: number
  QUIC_PUBLIC_RESETS_POST_HANDSHAKE: number
  QUIC_QPACK_DECODER_STREAM_ERROR: number
  QUIC_QPACK_DECODER_STREAM_IMPOSSIBLE_INSERT_COUNT: number
  QUIC_QPACK_DECODER_STREAM_INCORRECT_ACKNOWLEDGEMENT: number
  QUIC_QPACK_DECODER_STREAM_INCREMENT_OVERFLOW: number
  QUIC_QPACK_DECODER_STREAM_INTEGER_TOO_LARGE: number
  QUIC_QPACK_DECODER_STREAM_INVALID_ZERO_INCREMENT: number
  QUIC_QPACK_DECOMPRESSION_FAILED: number
  QUIC_QPACK_ENCODER_STREAM_DUPLICATE_DYNAMIC_ENTRY_NOT_FOUND: number
  QUIC_QPACK_ENCODER_STREAM_DUPLICATE_INVALID_RELATIVE_INDEX: number
  QUIC_QPACK_ENCODER_STREAM_ERROR: number
  QUIC_QPACK_ENCODER_STREAM_ERROR_INSERTING_DYNAMIC: number
  QUIC_QPACK_ENCODER_STREAM_ERROR_INSERTING_LITERAL: number
  QUIC_QPACK_ENCODER_STREAM_ERROR_INSERTING_STATIC: number
  QUIC_QPACK_ENCODER_STREAM_HUFFMAN_ENCODING_ERROR: number
  QUIC_QPACK_ENCODER_STREAM_INSERTION_DYNAMIC_ENTRY_NOT_FOUND: number
  QUIC_QPACK_ENCODER_STREAM_INSERTION_INVALID_RELATIVE_INDEX: number
  QUIC_QPACK_ENCODER_STREAM_INTEGER_TOO_LARGE: number
  QUIC_QPACK_ENCODER_STREAM_INVALID_STATIC_ENTRY: number
  QUIC_QPACK_ENCODER_STREAM_SET_DYNAMIC_TABLE_CAPACITY: number
  QUIC_QPACK_ENCODER_STREAM_STRING_LITERAL_TOO_LONG: number
  QUIC_SERVER_UNHEALTHY: number
  QUIC_SILENT_IDLE_TIMEOUT: number
  QUIC_STALE_CONNECTION_CANCELLED: number
  QUIC_STREAMS_BLOCKED_DATA: number
  QUIC_STREAMS_BLOCKED_ERROR: number
  QUIC_STREAM_DATA_AFTER_TERMINATION: number
  QUIC_STREAM_DATA_BEYOND_CLOSE_OFFSET: number
  QUIC_STREAM_LENGTH_OVERFLOW: number
  QUIC_STREAM_MULTIPLE_OFFSET: number
  QUIC_STREAM_SEQUENCER_INVALID_STATE: number
  QUIC_TLS_BAD_CERTIFICATE: number
  QUIC_TLS_CERTIFICATE_EXPIRED: number
  QUIC_TLS_CERTIFICATE_REQUIRED: number
  QUIC_TLS_CERTIFICATE_REVOKED: number
  QUIC_TLS_CERTIFICATE_UNKNOWN: number
  QUIC_TLS_INTERNAL_ERROR: number
  QUIC_TLS_KEYING_MATERIAL_EXPORTS_MISMATCH: number
  QUIC_TLS_KEYING_MATERIAL_EXPORT_NOT_AVAILABLE: number
  QUIC_TLS_UNEXPECTED_KEYING_MATERIAL_EXPORT_LABEL: number
  QUIC_TLS_UNRECOGNIZED_NAME: number
  QUIC_TLS_UNSUPPORTED_CERTIFICATE: number
  QUIC_TOO_MANY_AVAILABLE_STREAMS: number
  QUIC_TOO_MANY_BUFFERED_CONTROL_FRAMES: number
  QUIC_TOO_MANY_CONNECTION_ID_WAITING_TO_RETIRE: number
  QUIC_TOO_MANY_OPEN_STREAMS: number
  QUIC_TOO_MANY_OUTSTANDING_RECEIVED_PACKETS: number
  QUIC_TOO_MANY_OUTSTANDING_SENT_PACKETS: number
  QUIC_TOO_MANY_RTOS: number
  QUIC_TOO_MANY_SESSIONS_ON_SERVER: number
  QUIC_TOO_MANY_STREAM_DATA_INTERVALS: number
  QUIC_TRANSPORT_INVALID_CLIENT_INDICATION: number
  QUIC_TRY_TO_WRITE_DATA_ON_READ_UNIDIRECTIONAL_STREAM: number
  QUIC_UNENCRYPTED_FEC_DATA: number
  QUIC_UNENCRYPTED_STREAM_DATA: number
  QUIC_UNEXPECTED_DATA_BEFORE_ENCRYPTION_ESTABLISHED: number
  QUIC_UNSUPPORTED_PROOF_DEMAND: number
  QUIC_VERSION_NEGOTIATION_MISMATCH: number
  QUIC_WINDOW_UPDATE_RECEIVED_ON_READ_UNIDIRECTIONAL_STREAM: number
  QUIC_ZERO_RTT_REJECTION_LIMIT_REDUCED: number
  QUIC_ZERO_RTT_RESUMPTION_LIMIT_REDUCED: number
  QUIC_ZERO_RTT_UNRETRANSMITTABLE: number
}

interface QuicRstStreamError {
  QUIC_APPLICATION_DONE_WITH_STREAM: number
  QUIC_BAD_APPLICATION_PAYLOAD: number
  QUIC_DATA_AFTER_CLOSE_OFFSET: number
  QUIC_DUPLICATE_PROMISE_URL: number
  QUIC_ERROR_PROCESSING_STREAM: number
  QUIC_HEADERS_TOO_LARGE: number
  QUIC_INVALID_PROMISE_METHOD: number
  QUIC_INVALID_PROMISE_URL: number
  QUIC_MULTIPLE_TERMINATION_OFFSETS: number
  QUIC_PROMISE_VARY_MISMATCH: number
  QUIC_PUSH_STREAM_TIMED_OUT: number
  QUIC_REFUSED_STREAM: number
  QUIC_RST_ACKNOWLEDGEMENT: number
  QUIC_STREAM_CANCELLED: number
  QUIC_STREAM_CLOSED_CRITICAL_STREAM: number
  QUIC_STREAM_CONNECTION_ERROR: number
  QUIC_STREAM_CONNECT_ERROR: number
  QUIC_STREAM_DECODER_STREAM_ERROR: number
  QUIC_STREAM_DECOMPRESSION_FAILED: number
  QUIC_STREAM_ENCODER_STREAM_ERROR: number
  QUIC_STREAM_EXCESSIVE_LOAD: number
  QUIC_STREAM_FRAME_ERROR: number
  QUIC_STREAM_FRAME_UNEXPECTED: number
  QUIC_STREAM_GENERAL_PROTOCOL_ERROR: number
  QUIC_STREAM_ID_ERROR: number
  QUIC_STREAM_INTERNAL_ERROR: number
  QUIC_STREAM_MISSING_SETTINGS: number
  QUIC_STREAM_NO_ERROR: number
  QUIC_STREAM_PEER_GOING_AWAY: number
  QUIC_STREAM_REQUEST_INCOMPLETE: number
  QUIC_STREAM_REQUEST_REJECTED: number
  QUIC_STREAM_SETTINGS_ERROR: number
  QUIC_STREAM_STREAM_CREATION_ERROR: number
  QUIC_STREAM_TTL_EXPIRED: number
  QUIC_STREAM_UNKNOWN_APPLICATION_ERROR_CODE: number
  QUIC_STREAM_VERSION_FALLBACK: number
  QUIC_STREAM_WEBTRANSPORT_BUFFERED_STREAMS_LIMIT_EXCEEDED: number
  QUIC_STREAM_WEBTRANSPORT_SESSION_GONE: number
  QUIC_UNAUTHORIZED_PROMISE_URL: number
}

interface SecureDnsMode {
  Automatic: number
  Off: number
  Secure: number
}

// export enum NetlogPhase {
//   PHASE_NONE = 0,
//   PHASE_BEGIN = 1,
//   PHASE_END = 2
// }

export type NetlogPhase = number   // TODO: probably a better way to do this with an enum

export interface NetlogEvent<T> {
  params?: T
  phase: NetlogPhase
  source: NetlogSource
  time: string
  type: number
}

// // Disabled because we don't want dynamic access like this to all possibilities
// interface NetlogParams {
//   servers?: any[]
//   version: any
//   type: any
//   reason?: string
//   net_error?: number
//   byte_count?: number
//   bytes?: string
//   source_dependency?: SourceDependency
//   local_address?: string
//   remote_address?: string
//   address?: string
//   address_list?: string[]
//   aliases?: any[]
//   results?: Results
//   cached?: boolean
//   ipv6_available?: boolean
//   allow_cached_response?: boolean
//   dns_query_type?: number
//   host?: string
//   is_speculative?: boolean
//   network_anonymization_key?: string
//   secure_dns_policy?: number
//   error_lib?: number
//   error_reason?: number
//   file?: string
//   line: any
//   ssl_error?: number
//   backup_job?: boolean
//   group_id?: string
//   should_wait?: boolean
//   expect_spdy?: boolean
//   original_url?: string
//   priority?: string
//   url?: string
//   using_quic?: boolean
//   proxy_server?: string
//   pac_string?: string
//   is_preconnect?: boolean
//   privacy_mode?: string
//   initiator?: string
//   load_flags?: number
//   method?: string
//   network_isolation_key?: string
//   request_type?: string
//   site_for_cookies?: string
//   upload_id?: string
//   traffic_annotation?: number
//   preflight_required?: boolean
//   cors_preflight_policy?: string
//   headers: any
//   is_revalidating?: boolean
//   cipher_suite?: number
//   encrypted_client_hello?: boolean
//   is_resumed?: boolean
//   key_exchange_group?: number
//   next_proto?: string
//   peer_signature_algorithm?: number
//   cert_status?: number
//   is_issued_by_known_root?: boolean
//   public_key_hashes?: string[]
//   scts: any
//   verified_cert?: VerifiedCert
//   embedded_scts?: string
//   scts_from_ocsp_response?: string
//   scts_from_tls_extension?: string
//   best_result_index?: number
//   has_valid_path?: boolean
//   certificates?: string[]
//   is_valid?: boolean
//   last_cert_trust?: string
//   digest_policy?: number
//   certificate?: string
//   crlset_sequence?: number
//   verify_flags?: number
//   verifier_flags?: number
//   num_sockets?: number
//   buf_len?: number
//   index?: number
//   offset?: number
//   bytes_copied?: number
//   client_address_space?: string
//   resource_address_space?: string
//   result?: string
//   key?: string
//   entry_hash?: string
//   filters?: string
//   truncate?: boolean
//   proto?: string
//   ocsp_response?: string
//   attempt_number?: number
//   hostname?: string
//   query_type?: number
//   secure?: boolean
//   transactions_needed?: TransactionsNeeded[]
//   dns_query_types?: string[]
//   secure_dns_mode?: number
//   new_config?: NewConfig
//   persistence?: boolean
//   persistent_store?: boolean
//   get_sts_state_result?: boolean
//   host_found_in_hsts_bypass_list?: boolean
//   should_upgrade_to_ssl?: boolean
//   allow_dns_over_https_upgrade?: boolean
//   append_to_multi_label_name?: boolean
//   attempts?: number
//   can_use_insecure_dns_transactions?: boolean
//   can_use_secure_dns_transactions?: boolean
//   dns_over_tls_active?: boolean
//   dns_over_tls_hostname?: string
//   doh_attempts?: number
//   doh_config?: DohConfig
//   nameservers?: string[]
//   ndots?: number
//   num_hosts?: number
//   rotate?: boolean
//   search?: any[]
//   timeout?: number
//   unhandled_options?: boolean
//   use_local_ipv6?: boolean
// }

interface SourceDependency {
  id: number
  type: number
}

interface Results {
  aliases: any[]
  expiration: string
  ip_endpoints: IpEndpoint[]
}

interface IpEndpoint {
  endpoint_address: string
  endpoint_port: number
}

interface VerifiedCert {
  certificates: string[]
}

interface TransactionsNeeded {
  dns_query_type: number
}

interface NewConfig {
  single_proxy: string[]
}

interface DohConfig {
  servers: any[]
}

interface NetlogSource {
  id: number
  start_time: string
  type: number
}
