// File is autogenerated using:
//   supabase start && supabase gen types typescript --db-url "postgres://postgres:XXXXXXXX@db.YYYYYYYYYY.supabase.co:6543/postgres"
//   [ ! -f .env.local ] || export $(grep -v '^#' .env.local | xargs) ; supabase start && supabase gen types typescript --db-url "$SUPABASE_POSTGRES_DB"
//
// DO NOT EDIT MANUALLY

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json }
  | Json[];

export interface Database {
  public: {
    Tables: {
      searches: {
        Row: {
          id: number;
          created_at: string;
          user_id: string | null;
          query: string;
          user_email: string | null;
        };
        Insert: {
          id?: number;
          created_at?: string;
          user_id?: string | null;
          query?: string;
          user_email?: string | null;
        };
        Update: {
          id?: number;
          created_at?: string;
          user_id?: string | null;
          query?: string;
          user_email?: string | null;
        };
      };
      cloudstate: {
        Row: {
          user_id: string;
          key: string;
          value: Json;
        };
        Insert: {
          user_id?: string;
          key: string;
          value: Json;
        };
        Update: {
          user_id?: string;
          key?: string;
          value?: Json;
        };
      };
    };
    Functions: {};
  };
}
