// File is autogenerated using:
//   supabase gen types typescript --db-url "postgres://postgres:XXXXXXXX@db.YYYYYYYYYY.supabase.co:6543/postgres"
//
// DO NOT EDIT

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json }
  | Json[];

export interface Database {
  public: {
    Tables: {
      searches: {
        Row: {
          id: number;
          created_at: string;
          user_id: string | null;
          query: string;
          user_email: string | null;
        };
        Insert: {
          id?: number;
          created_at?: string;
          user_id?: string | null;
          query?: string;
          user_email?: string | null;
        };
        Update: {
          id?: number;
          created_at?: string;
          user_id?: string | null;
          query?: string;
          user_email?: string | null;
        };
      };
    };
    Functions: {};
  };
}
