import { fromPlaywrightDetails, FiltersEngine, NetworkFilter } from "@cliqz/adblocker-playwright"
import { readFileSync } from "node:fs"
import { BrowserContext } from "playwright"

export const enableBlockingForContext = async (context: BrowserContext, extraUrls?: string[], showBlocked: boolean = false) => {
  const engine = FiltersEngine.parse(readFileSync("adblock.txt", "utf-8"))     // Generated by the Dockerfile
  engine.update({ newNetworkFilters: extraUrls?.map((url) => NetworkFilter.parse(url)!) })

  await context.route("**/*", route => {
    const adblockReq = fromPlaywrightDetails(route.request())
    const engineMatch = engine.match(adblockReq)
    if (engineMatch.match) {
      if (showBlocked) console.log("\x1b[37mBLOCKING: ", route.request().url(), "\x1b[0m")
      return route.abort()
    }
    return route.fallback()
  })
}
